### ISSUE TITLE
Publishing Relationships?

### ISSUE THREAD

**Issue by AdamKyle** [promiscuous-io/promiscuous#50] opened 2014-04-29 14:40 UTC
If I have a  publisher model of user with:

`has_many_and_belongs_to :roles, through :roles_users`

and a publisher model of roles with:

`has_many_and_belongs_to :users, through :roles_users`

and then set up the subscriber models with the same relationships and tell it to listen to the publisher models, if the publisher app seeds it's own database with:

```
User.create(:first_name => 'fsdfdsf', :last_name => 'sdfsd', :user_name => 'sdfdsf', :email => 'sdfdsf@email.com',
Role.create(:role => 'Administrator', :role => 'Member')
User.find_by(first_name: 'fsdfdsf').role = 'Administrator'
```

What happens is that the user and the role are create in the subscriber database, how ever that relationship is not created. So I guess my question is - how do you publish, using active record and PostgreSQL relationships (I know active record is in beta for this gem)
- The join table is created in both pub and sub.

**also as a side not**

Your documentation is wrong on having to sync database between pub and sub. If you have 8 records in pub and start sub, sub will auto sync to pub. Please consider updating the docs as their is no `sync` method on `promiscuous`

**Comment by kareemk** [comment] 2014-04-30 14:42
@AdamKyle this _should_ work by creating a model, on both the pub and sub, that matches the name of the join table and publishing the two foreign keys. I'll investigate this soon but feel free to give it a try.

How did you try and sync? You only need to sync if you haven't setup and started the subscriber before creating records in the publisher (which in practice is almost always the case). There is a sync method on promiscuous on each instance in a model e.g. to sync all of your users in console you would do:

``` ruby
User.all.each { |u| u.promiscuous.sync }
```

Or alternatively you can use the command line util:

```
promiscuous publish "User.all"
```

**Comment by AdamKyle** [comment] 2014-04-30 15:10
@kareemk 

I will def give it a try. In the mean time I wrote a rake method that creates the relationship after the sub recieves the pubs attributes for given models.

As for part two. I found that A) the given example for syncing a user states: unknown method sync for promiscuous, and when using the trace to search for the method, the module the method is suppose to be in exists, but the actual sync method does not... (maybe I missing something? - I can give you the trace if you need).

How ever I will also try the command line example. (maybe its just me that's broken LOL)

**Comment by kareemk** [comment] 2014-04-30 15:19
@AdamKyle ah, the issue is that sync is not supported for activerecord **yet**.  I've created #52 to track.

**Comment by AdamKyle** [comment] 2014-04-30 15:22
Understood, thank you.

**Comment by kareemk** [comment] 2014-05-23 16:43
Moving to next version. @AdamKyle let me know if the workaround worked.

**Comment by AdamKyle** [comment] 2014-05-23 16:46
I never actually tried it to be honest. I used a custom rake command to create a the relationship. How goes the Active Record Sync concept?

**Comment by kareemk** [comment] 2014-05-23 16:47
ActiveRecord sync is supported on the latest version.

**Comment by AdamKyle** [comment] 2014-05-23 17:10
YES! you are god. let me try this tonight and ill let you know :D :dancer:

**Comment by kareemk** [comment] 2014-05-23 18:08
Make sure to either point your gemfile to master or '1.0.0.beta2'

**Comment by kareemk** [comment] 2014-05-23 21:22
Make that '1.0.0.beta3'

**Comment by AdamKyle** [comment] 2014-05-27 05:30
I think I am doing this wrong. 

So In the subscribers.rb (on the subscriber app) I did:

```
User.all.each { |u| u.promiscuous.sync }
Role.all.each { |r| r.promiscuous.sync }
```

Which I assume - based on the docs - would say: Go to the publisher, grab me every user and role object and sync them over here.

Which confuses me because on the Publisher side I do:

```
  publish Xaaron::User do
    attributes :first_name, :last_name, :email, :user_name, :auth_token, :as => :User
  end
```

So.....How do you sync something like this?

But I got the error:

```
/Users/Adam/.rvm/gems/ruby-2.0.0-p353/gems/activemodel-4.1.0/lib/active_model/attribute_methods.rb:435:in `method_missing': undefined method `promiscuous' for #<User:0x007fc9c4cac660> (NoMethodError)
```

I find this odd because in the User Model:

```
class User < ActiveRecord::Base
  include Promiscuous::Subscriber
  subscribe :first_name, :email, :user_name, :last_name, :auth_token

  ...

end
```

And it subscribes fine, it saves the data that is published fine ... 

This error occurred after trying to do `rails s` on the subscriber. I much prefer to do this programatically then by console commands. Any idea if this is just me failing to read or if its an actual bug?

Note: I am running the latest and greatest from master which shows 1.0.0.beta2

**Comment by kareemk** [comment] 2014-05-27 15:07
Your publisher side code doesn't look correct. It should be something like (in the model file):

``` ruby
class Xaaron::User < ActiveRecord::Base
  publish :first_name, :last_name, :email, :user_name, :auth_token, :as => :User
end
```

**Comment by AdamKyle** [comment] 2014-05-27 15:11
The publisher code is inside of the `config/publishers.rb` as per [this documentation you have](https://github.com/promiscuous-io/promiscuous/wiki/Features-and-Recipes#in-a-config-file)

My subscriber subscribes from the model instead of the `config/subscribers.rb`

I can do the sync from the terminal by doing `bundle exec promiscuous "Xaaron::User.all"` but I cant seem to do it programatically as I pointed out.

Are you phasing out the subscribers.rb and publishers.rb from the config directory?

**Comment by kareemk** [comment] 2014-05-27 16:02
Ah, I didn't realize that you were using subscribers.rb and publishers.rb.

Looks like you have the syntax wrong in publishers.rb. It should  be:

``` ruby
Promiscuous.define do
  publish ':xaaron/users', :as => :User do
     attributes :first_name, :last_name, :email, :user_name, :auth_token
  end
end
```

**Comment by AdamKyle** [comment] 2014-05-27 18:42
That's not what I have, I have the following:

**Publisher App:**

```
Promiscuous.define do
  publish Xaaron::User do
    attributes :first_name, :last_name, :email, :user_name, :auth_token, :as => :User
  end

  publish Xaaron::ApiKey do
    attributes :xaaron_users_id, :api_key, :as => :ApiKey
  end

  publish Xaaron::Role do
    attributes :role, :as => :Role
  end

  publish Xaaron::Permission do
    attributes :permission, :as => :Permission
  end
end
```

Then on the subscriber side, I subscribe through the models, So ill show you the user for example:

**Subscriber**

```
class User < ActiveRecord::Base
  include Promiscuous::Subscriber
  subscribe :first_name, :email, :user_name, :last_name, :auth_token
  # code here
end
```

This **works as is**, when a model is published it is gathered, in this case the user subscribes and collects the data it's listening too. This part **works**. Where we fall apart is, in the subscriber app under the `config/subscribers.rb` I decided to write the following:

```
Promiscuous.define do
  User.all.each { |u| u.promiscuous.sync }
end
```

How ever when starting up the subscriber app I get the following error:

```
/Users/Adam/.rvm/gems/ruby-2.0.0-p353/gems/activemodel-4.1.0/lib/active_model/attribute_methods.rb:435:in `method_missing': undefined method `promiscuous' for #<User:0x007fc9c4cac660> (NoMethodError)
```

The subscriber app **will work** if I comment out the code I added to `config/subscribers.rb` By work I mean the subscriber app will start up when doing `rails s`

Why can I not sync this way? This is the issue I am trying to solve. Currently Subscribing and publishing works the way I showed you, but syncing (in the matter I showed you) does not work.

**Comment by kareemk** [comment] 2014-05-28 01:42
Ah! You can't do that on the subscriber, you need to do that in the publisher in console (as it should only need to happen once for existing data).

**Comment by AdamKyle** [comment] 2014-05-28 01:44
That's where I originally tried it and I got the same error so I thought ok lets do this on te subscriber and well here we are

**Closed as completed** 2014-07-07 21:37 UTC
Labels: enhancement
